name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [28.x, 20.x, 22.x]

    steps:
    - name: Clone GitHub repository on the runner machine
      uses: actions/checkout@v4
    - name: Use Node.js ${{node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{node-version}}
        cache: 'npm'
    - name: Install Node packages
      run: npm ci
    - name: Run Integration Tests
      run: npm test
